### ISSUE TITLE
`set_subpart!` for unique indexed attributes

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/ACSets.jl#13]
Possibly undesired behavior: setting a subpart of a unique indexed attribute does so in a particular order (rather than all at once), leading to spurious uniqueness errors.  

```julia
@present TheoryLabeledGraph <: TheoryGraph begin
  Label::AttrType
  label::Attr(V,Label)
end
@acset_type IndexedLabeledGraph(TheoryLabeledGraph, index=[:src,:tgt],
                                unique_index=[:label]) <: AbstractGraph
z = @acset IndexedLabeledGraph{Int} begin 
       V=2 
       label=[2,1] 
end
set_subpart!(z, :label,[1,2])
ERROR: AssertionError: subpart not unique
```

**Comment by slwu89** [comment]
Ran into this problem too recently. However, I'm not sure how to elegantly do a check at compile time since it appears that for `StructACSet` objects, information about which homs/attrs are indexed/uniquely indexed is not available in the type. It would appear the best way to proceed would be to include a runtime check in `_set_subpart!`, checking the type of the cache for that hom/attr implementation. Is my understanding correct?

**Comment by slwu89** [comment]
Looks like this issue can be closed now?
