### ISSUE TITLE
InterType dependencies

### ISSUE THREAD

**Issue by fivegrant** [AlgebraicJulia/ACSets.jl#77]
Could an InterType depend on another InterType outside of the file? For example, let's say I have the following directory structure:
```
proj/
  - shared.it
  - obj1/
    - obj1.it
  - obj2/
    - obj2.it
```
In this scenario, I'd want to be able to instantiate `obj1.it` and `obj2.it` in the same environment AND have them depend on the types defined in `shared.it`.

**Comment by jpfairbanks** [comment]
This is definitely an intended use case that should work. I think that this line https://github.com/AlgebraicJulia/ACSets.jl/blob/a7b19ffab6dc69afe4e7625f1dfb5f181e4ed65b/src/intertypes/InterTypes.jl#L77 introduces the `imports` field to allow an intertype module to refer to other intertype modules for exactly this purpose. It is an `OrderedDict` because Owen wants "last write wins" semantics for imports.

**Comment by olynch** [comment]
See: https://github.com/AlgebraicJulia/ACSets.jl/blob/146fa754f50eec128569eea0b6abfe9376610952/test/intertypes/InterTypes.jl#L44C1-L44C1.

**Comment by olynch** [comment]
It probably could be implemented more smoothly though.
