### ISSUE TITLE
InterTypes variants referring to locally defined variants

### ISSUE THREAD

**Issue by p-stokes** [AlgebraicJulia/ACSets.jl#87]
It might be useful to be able to define recursive sum types in InterTypes. Currently, the below example is not possible.

```
@sum Var begin
  Untyped(var::Symbol)
  Typed(var::Symbol, type::Symbol)
end

@sum UWDTerm begin
  Statement(relation::Symbol, variables::Vector{Var})
  UWDExpr(context::Vector{Var}, statements::Vector{Statement})
  UWDModel(header::String, uwd::UWDExpr)
end
```

**Comment by jpfairbanks** [comment]
The problem isn't the recursion. The following test case shows recursion support

```julia
@sum Const begin
  ConstStr(val::String)
  ConstInt(val::Int32)
  ConstBool(val::Bool)
end

@sum Term begin
  Constant(val::Const)
  Plus(terms::Vector{Term})
  IfThenElse(ifcase::Term, thencase::Term, elsecase::Term)
end

struct Assignment
  lhs::String
  rhs::Term
end
```

The problem is that a sum type variant can't refer to a previous variant. I identified that by deleting parts of the following code until it worked.

```julia
@sum UWDTerm begin
  Statement(relation::Symbol, variables::Vector{Var})
  UWDExpr(context::Vector{Var}, statements::Vector{Statement})
  UWDModel(header::String, uwd::UWDExpr)
end
```

The problem is that when processing `UWDTerm` the `InterTypes.parse_intertype_decl` is looking for a type called `Statement` which doesn't exist yet.

@olynch, this is a pretty big reason for using the `@data` macro. We had the ability to write really compact type specifications. You would be able to workaround it as follows. Except that InterTypes doesn't support subtyping relations.

```julia
@sum Var begin
  Untyped(var::Symbol)
  Typed(var::Symbol, type::Symbol)
end

struct Statement # <: UWDTerm
  relation::Symbol
  variables::Vector{Var}
end

struct UWDExpr # <: UWDTerm
  context::Vector{Var}
  statements::Vector{Statement}
end

struct UWDModel # <: UWDTerm
  header::String
  uwd::UWDExpr
end
```
